# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    wordpress:
        image: wordpress
        # этот образ будет общаться с mysql
        links:
            - mysql
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./www:/var/www/html   
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_PASSWORD: root
        networks:
            - back
    mysql:
        image: mysql:8
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - back
    phpmyadmin:
    #добавляем phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - back
networks:
    back:
volumes:
    db_data: